export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    fontFamily: 'Inter, sans-serif',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '2rem',
    width: '100%',
    maxWidth: '400px',
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
  },
  title: { fontSize: '24px', fontWeight: 700, marginBottom: '4px', color: '#111' },
  subtitle: { color: '#888', marginBottom: '1.5rem', fontSize: '14px' },
  form: { display: 'flex', flexDirection: 'column' as const, gap: '12px' },
  input: {
    padding: '12px 14px',
    borderRadius: '8px',
    border: '1px solid #e0e0e0',
    fontSize: '14px',
    outline: 'none',
  },
  button: {
    padding: '12px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#111',
    color: '#fff',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: '4px',
  },
  error: {
    backgroundColor: '#fff0f0',
    color: '#cc0000',
    padding: '10px 14px',
    borderRadius: '8px',
    fontSize: '13px',
    marginBottom: '12px',
  },
  link: { textAlign: 'center' as const, marginTop: '1rem', fontSize: '13px', color: '#666' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
  logoutBtn: {
    padding: '8px 14px',
    borderRadius: '8px',
    border: '1px solid #e0e0e0',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '13px',
  },
  profile: { display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    backgroundColor: '#111',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: 700,
  },
  name: { fontWeight: 600, fontSize: '16px', margin: 0 },
  email: { color: '#888', fontSize: '13px', margin: 0 },
  infoBox: {
    backgroundColor: '#f9f9f9',
    borderRadius: '8px',
    padding: '12px 14px',
    marginBottom: '8px',
  },
  infoLabel: { fontSize: '11px', color: '#888', margin: '0 0 2px', textTransform: 'uppercase' as const },
  infoValue: { fontSize: '13px', color: '#111', margin: 0, wordBreak: 'break-all' as const },
};